### PR TITLE
Changes to readme

### PR DESCRIPTION
**Pull request by Goro2030**

### CODE REVIEW

**Comment by Goro2030** [comment]
Van algunos cambios menores

**Review by iamjuarez — APPROVED** [review]

**Comment by Goro2030** [comment]
Will you merge them?

**Review by yerkobits — CHANGES_REQUESTED** [review]
I'm going to try the new version of Ubuntu, for choose a light setup.

**Review by yerkobits — APPROVED** [review]

**Comment by Goro2030** [comment]
I'm trying with apt-get install libboost1.67-dev
You also need to add to instructions to do:

apt install qt5-default  

(I'll do it now) :)

**Comment by Goro2030** [comment]
The boost1.67-dev alone does not work ... I did now download all 450 megabytes of libraries with:

`apt-get install libboost1.67-all-dev`

And it works... since I don't know which ones you use, cannot pick and choose the right ones...

**Comment by Goro2030** [comment]
@yerkobits , this pull request includes 4 changes, not only the README. Please review and approve at least the UI one ( version is wrong ) .

**Comment by yerkobits** [comment]
> @yerkobits , this pull request includes 4 changes, not only the README. Please review and approve at least the UI one ( version is wrong ) .

I setting a variable (on sourcecode) to automatic update version on UI

**Pull request merged**
