### PR TITLE
Prosus Money v0.7.2

### PR DESCRIPTION
**Pull request by prosus-money**
* automatic blockchain load
* antiasic
* seed nodes

### CODE REVIEW

**Comment by yerkobits** [comment]
this pull request is a CLI version
-> abort

**Comment by Goro2030** [comment]
YES!!! New version coming!!!! Please confirm the PULL so we can compile this one!

**Comment by Goro2030** [comment]
opppps sorry, just in time! :)

**Comment by yerkobits** [comment]
@Goro2030 
here, a GUI+CLI version
[Prosus Money v0.7.2-gui](https://github.com/ProsusCorp/prosus/pull/14)

**Pull request closed without merging**
